server:
  port: 20000
  tomcat:
    uri-encoding: UTF-8
dubbo:
  application:
    name: dubbo-provider
  registry:
    protocol: zookeeper
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 20880